version: ~> 1.0
language: node_js
node_js:
  - "8"
  - "10"
  - "12"
os:
  - linux

git:
  autocrlf: false

services:
  - docker

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-5
      - g++-5

before_install:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      export CC="gcc-5";
      export CXX="g++-5";
      export LINK="gcc-5";
      export LINKXX="g++-5";
    fi

before_script:
  npm run build:tezos-image

after_success:
  npm run coverage